### ISSUE TITLE
La versión del APK no se muestra correctamente

### ISSUE THREAD

**Issue by Gustavowgc** [procesoseficientes/sonde-presales#1]
dentro de la aplicación y al momento de verlo desde aplicaciones del telefono

![image](https://user-images.githubusercontent.com/64803356/95803542-9b5f5300-0cbd-11eb-9b6b-0728e1026088.png)

![image](https://user-images.githubusercontent.com/64803356/95803567-add98c80-0cbd-11eb-92be-e17d159c6f6a.png)

el correcto es 2020.10.7

**Comment by fabrv** [comment]
Arreglado
